name: Node.js Package

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Replace stable tag
        run: |
          chmod +x ./build.sh && ./build.sh
          rm -rf ./build.sh

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
